# Generated by Django 6.0 on 2025-12-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title.', unique=True)),
                ('image', models.CharField(help_text="Static image path, e.g., 'images/spices(1)(1).png'", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on the home page and products page.')),
                ('order', models.IntegerField(default=0, help_text='Order in which categories appear.')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nellore Maharuchulu', max_length=100)),
                ('phone', models.CharField(default='+91 8965756562', max_length=20)),
                ('whatsapp_number', models.CharField(default='918965756562', help_text="WhatsApp number without '+'. Used in links.", max_length=20)),
                ('contact_email', models.EmailField(default='info@nelloremaharuchulu.com', max_length=254)),
                ('location', models.CharField(default='Nellore, Andhra Pradesh', max_length=255)),
                ('copyright_holder', models.CharField(default='Nellore Maharuchulu', max_length=100)),
                ('hero_title', models.TextField(default='Taste the **Real** Andhra Tradition.', help_text="Use ** for bold text, rendered with 'safe' in template.")),
                ('hero_subtext', models.TextField(default='Home-crafted powders, pickles, and masalas straight from our kitchen to yours.')),
                ('tradition_title', models.CharField(default='The Taste of Tradition, Straight from Nellore', max_length=255)),
                ('tradition_paragraph1', models.TextField(default='At Nellore Maharuchulu, every spoonful brings you the authentic taste of Andhra’s rich culinary heritage. Handcrafted in small batches with family recipes passed down for generations.')),
                ('tradition_paragraph2', models.TextField(default='We don’t just sell products, we share family secrets. From our kitchen to yours, each laddu, each masala blend, and every jar of pickle is made using traditional methods and carefully sourced ingredients.')),
                ('best_sellers_title', models.CharField(default='Our Best Sellers', max_length=255)),
                ('best_sellers_subtitle', models.CharField(default='Tried, loved, and reordered. Here are the top picks our customers can’t get enough of.', max_length=255)),
                ('still_craving_title', models.CharField(default='Still Craving Home-style Goodness?', max_length=255)),
                ('still_craving_subtext', models.CharField(default='Discover our full range of spice powders, pickles, sweets, and instant mixes.', max_length=255)),
                ('footer_description', models.TextField(default='Authentic Andhra flavors prepared with love, care, and family tradition. Homemade spice powders, pickles, sweets and more — straight from Nellore.')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(help_text="Static image path, e.g., 'images/product_avakai.png'", max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in Indian Rupees (₹)', max_digits=10)),
                ('unit', models.CharField(default='kg', help_text="e.g., 'kg', 'piece', 'box'", max_length=50)),
                ('is_best_seller', models.BooleanField(default=False, help_text="Check to display in the 'Best Sellers' section on the homepage.")),
                ('order', models.IntegerField(default=0, help_text="Order within the 'Best Sellers' section.")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['order', 'name'],
            },
        ),
    ]
