# Generated by Django 6.0 on 2025-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_description',
            field=models.TextField(),
        ),
    ]
