# Generated by Django 6.0 on 2025-12-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesetting_footer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='best_sellers_subtitle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='best_sellers_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copyright_holder',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='still_craving_subtext',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='still_craving_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tradition_paragraph1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tradition_paragraph2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tradition_title',
            field=models.CharField(max_length=255),
        ),
    ]
