# Generated by Django 6.0 on 2025-12-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesetting_best_sellers_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Used in the URL, e.g., 'refund-policy'", unique=True)),
                ('content', models.TextField(help_text='Full HTML content for the policy page.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Static Policy Page',
                'verbose_name_plural': 'Static Policy Pages',
            },
        ),
    ]
