# Generated by Django 6.0 on 2025-12-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_logo',
            field=models.ImageField(blank=True, help_text='Upload the image for the Footer logo.', null=True, upload_to='site_logos/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='navbar_logo',
            field=models.ImageField(blank=True, help_text='Upload the image for the main Navbar logo.', null=True, upload_to='site_logos/'),
        ),
    ]
