# Generated by Django 6.0 on 2025-12-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_footer_logo_sitesetting_navbar_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_main_title', models.CharField(default='About Nellore Maharuchulu', max_length=255)),
                ('about_subtitle', models.CharField(default='Bringing the flavors of Andhra’s kitchens to your home.', max_length=255)),
                ('about_main_image', models.ImageField(help_text='Large image for the main story section.', upload_to='about/')),
                ('about_story_title', models.CharField(default='Homemade Flavours, Straight from Nellore', max_length=255)),
                ('about_story_p1', models.TextField(default='What started in our family kitchen is now reaching kitchens across the country. Nellore Maharuchulu was born from a simple idea...')),
                ('about_story_p2', models.TextField(default='From sun-dried spice powders to oil-cured pickles and hand-rolled laddus, every item is prepared using locally sourced ingredients and age-old recipes...')),
                ('why_choose_title', models.CharField(default='Why Choose Us', max_length=255)),
                ('why_choose_subtitle', models.TextField(default='At Nellore Maharuchulu, we don’t just make food — we preserve tradition...')),
                ('taste_title', models.CharField(default='Ready to Taste the Tradition?', max_length=255)),
                ('taste_desc', models.CharField(default='Browse our handmade spice powders, pickles, laddus, and more — and order easily through WhatsApp.', max_length=255)),
                ('taste_image', models.ImageField(help_text='Small spice stack image for the CTA section.', upload_to='about/cta/')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=300)),
                ('icon', models.ImageField(help_text='Small icon image for the card (e.g., 48x48)', upload_to='about/icons/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Reason',
                'verbose_name_plural': 'Why Choose Reasons',
                'ordering': ['order'],
            },
        ),
    ]
