# Generated by Django 6.0 on 2025-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_heading', models.CharField(default='We’re Just a Message Away', max_length=200)),
                ('contact_description', models.TextField(default='From spicy powders to sweet laddus, we’re here to talk about it all. Message us on WhatsApp or call.', help_text='The descriptive paragraph under the main contact heading.')),
                ('contact_image', models.ImageField(default='images/spices2.jpg', help_text='Image displayed next to the contact details.', upload_to='page_images/')),
                ('best_sellers_title', models.CharField(default='Our Best Sellers', max_length=150)),
                ('best_sellers_subtitle', models.CharField(default='Tried, loved, and reordered. Here are the top picks our customers can’t get enough of.', max_length=255)),
                ('taste_title', models.CharField(default='Taste the Difference with Nellore Maharuchulu', max_length=150)),
                ('taste_desc', models.CharField(default='Discover our full range of spice powders, pickles, sweets, and instant mixes.', max_length=255)),
                ('taste_image', models.ImageField(default='images/top-view-condiments-frame-with-copy-space-Photoroom.png', help_text='Image displayed next to the final CTA text.', upload_to='page_images/')),
            ],
            options={
                'verbose_name': 'Contact Page Setting',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
