# Generated by Django 6.0 on 2025-12-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='contact_page_subtext',
            field=models.CharField(default='We’d love to hear from you — whether it’s for orders, feedback, or questions about our products.', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='contact_us_title',
            field=models.CharField(default='Contact Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='contact_description',
            field=models.TextField(help_text='The descriptive paragraph under the main contact heading.'),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='contact_heading',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpagesettings',
            name='contact_image',
            field=models.ImageField(help_text='Image displayed next to the contact details.', upload_to='page_images/'),
        ),
    ]
