# Generated by Django 6.0 on 2025-12-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactpagesettings_contact_page_subtext_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactPageSettings',
        ),
    ]
