# Generated by Django 6.0 on 2025-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_contactpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_us_title', models.CharField(default='Contact Us', help_text='The main title at the top of the contact page.', max_length=100)),
                ('contact_page_subtext', models.TextField(default='We’d love to hear from you — whether it’s for orders, feedback, or questions about our products.', help_text='The descriptive subtext under the main Contact Us title.')),
                ('contact_heading', models.CharField(default='We’re Just a Message Away', help_text='The main heading for the contact details section.', max_length=200)),
                ('contact_description', models.TextField(default='Our team is dedicated to bringing you the best flavors and service. Reach out to us via phone, email, or visit our location during business hours.', help_text='The descriptive paragraph under the main contact heading.')),
                ('contact_image', models.ImageField(help_text='Image displayed next to the contact details (e.g., a hand-made item photo).', upload_to='page_images/')),
                ('best_sellers_title', models.CharField(default='Tried and Tested', help_text='Title for the best sellers section on the contact page.', max_length=150)),
                ('best_sellers_subtitle', models.CharField(default="See what everyone's ordering right now—the best of Nellore Maharuchulu.", help_text='Subtitle for the best sellers section on the contact page.', max_length=255)),
                ('taste_title', models.CharField(default='Ready to Taste the Tradition?', help_text='Title for the final call-to-action bar.', max_length=150)),
                ('taste_desc', models.CharField(default='Browse our handmade spice powders, pickles, sweets, and instant mixes.', help_text='Description for the final call-to-action bar.', max_length=255)),
                ('taste_image', models.ImageField(default='images/top-view-condiments-frame-with-copy-space-Photoroom.png', help_text='Image displayed next to the final CTA text.', upload_to='page_images/')),
            ],
            options={
                'verbose_name': 'Contact Page Setting',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
