# Generated by Django 6.0 on 2025-12-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactpagesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Large image for the product.', null=True, upload_to='products/'),
        ),
    ]
