# Generated by Django 6.0 on 2025-12-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
