# Generated by Django 6.0 on 2025-12-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Product image for the product.', null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Product image for the product.', null=True, upload_to='products_images/'),
        ),
    ]
