# Generated by Django 6.0 on 2025-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_category_image_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, help_text='Category image for the Categories Section.', null=True, upload_to='category_images/'),
        ),
    ]
