# Generated by Django 6.0 on 2025-12-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_category_image_alter_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload the hero image for the homepage.', null=True, upload_to='site_images/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='still_craving_image',
            field=models.ImageField(blank=True, help_text='Upload the still creaving section image for the homepage', null=True, upload_to='site_images/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tradition_image',
            field=models.ImageField(blank=True, help_text='Upload the tradition image for the homepage', null=True, upload_to='site_images/'),
        ),
    ]
