# Generated by Django 6.0 on 2025-12-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_sitesetting_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='products_subtitle',
            field=models.TextField(default='Discover everything we make with care, love, and authentic Andhra taste.', help_text='Subtitle for the products section.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='products_title',
            field=models.CharField(default='Explore Our Products', help_text='Title for the products section on the homepage.', max_length=255),
        ),
    ]
